### ISSUE TITLE
Minefob creating instance

### ISSUE THREAD

**Issue by kruemmelbande** [thefivesixfive/Minefob#1]
So, i tried to use it, but not even the example works.
It gives me the error
  NameError: name 'Minefob' is not defined
every time.
I did install Minefob, and i did import it, but it doesnt seem to do anything

**Comment by thefivesixfive** [comment]
Write `minefob.Minefob()` instead of just minefob, or use `from minefob import Minefob`. Documentation is flawed and will be fixed soon.

**Comment by thefivesixfive** [comment]
READMEs updated, as well as wiki, to correctly reflect code.
